version: "3"
services: 
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "127.0.0.1:8086:8086"        
    env_file:
      - 'env.influxdb'
    volumes:
      - "influxdb-data:/var/lib/influxdb"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    volumes:
      - "grafana-data:/var/lib/grafana"
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - "node-red-data:/data"

volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:

